// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package anycable is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	ConnectionRequest
	ConnectionResponse
	CommandMessage
	CommandResponse
*/
package anycable

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_ERROR   Status = 0
	Status_SUCCESS Status = 1
)

var Status_name = map[int32]string{
	0: "ERROR",
	1: "SUCCESS",
}
var Status_value = map[string]int32{
	"ERROR":   0,
	"SUCCESS": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConnectionRequest struct {
	Path    string            `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ConnectionRequest) Reset()                    { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()               {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectionRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type ConnectionResponse struct {
	Status      Status `protobuf:"varint,1,opt,name=status,enum=anycable.Status" json:"status,omitempty"`
	Identifiers string `protobuf:"bytes,2,opt,name=identifiers" json:"identifiers,omitempty"`
}

func (m *ConnectionResponse) Reset()                    { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()               {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CommandMessage struct {
	Command               string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Identifier            string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	ConnectionIdentifiers string `protobuf:"bytes,3,opt,name=connection_identifiers,json=connectionIdentifiers" json:"connection_identifiers,omitempty"`
	Data                  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *CommandMessage) Reset()                    { *m = CommandMessage{} }
func (m *CommandMessage) String() string            { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()               {}
func (*CommandMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CommandResponse struct {
	Status      Status `protobuf:"varint,1,opt,name=status,enum=anycable.Status" json:"status,omitempty"`
	Disconnect  bool   `protobuf:"varint,2,opt,name=disconnect" json:"disconnect,omitempty"`
	StopStreams bool   `protobuf:"varint,3,opt,name=stop_streams,json=stopStreams" json:"stop_streams,omitempty"`
	StreamFrom  bool   `protobuf:"varint,4,opt,name=stream_from,json=streamFrom" json:"stream_from,omitempty"`
	StreamId    string `protobuf:"bytes,5,opt,name=stream_id,json=streamId" json:"stream_id,omitempty"`
}

func (m *CommandResponse) Reset()                    { *m = CommandResponse{} }
func (m *CommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()               {}
func (*CommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*ConnectionRequest)(nil), "anycable.ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "anycable.ConnectionResponse")
	proto.RegisterType((*CommandMessage)(nil), "anycable.CommandMessage")
	proto.RegisterType((*CommandResponse)(nil), "anycable.CommandResponse")
	proto.RegisterEnum("anycable.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for RPC service

type RPCClient interface {
	Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	Subscribe(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error)
	Unsubscribe(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error)
	Perform(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := grpc.Invoke(ctx, "/anycable.RPC/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Subscribe(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/anycable.RPC/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Unsubscribe(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/anycable.RPC/Unsubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Perform(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/anycable.RPC/Perform", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPC service

type RPCServer interface {
	Connect(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	Subscribe(context.Context, *CommandMessage) (*CommandResponse, error)
	Unsubscribe(context.Context, *CommandMessage) (*CommandResponse, error)
	Perform(context.Context, *CommandMessage) (*CommandResponse, error)
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anycable.RPC/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Connect(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anycable.RPC/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Subscribe(ctx, req.(*CommandMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anycable.RPC/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Unsubscribe(ctx, req.(*CommandMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Perform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Perform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anycable.RPC/Perform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Perform(ctx, req.(*CommandMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anycable.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _RPC_Connect_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _RPC_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _RPC_Unsubscribe_Handler,
		},
		{
			MethodName: "Perform",
			Handler:    _RPC_Perform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x97, 0x76, 0x6d, 0x9a, 0x97, 0x69, 0x94, 0x27, 0x40, 0xa1, 0x43, 0x50, 0x72, 0xaa,
	0x38, 0xf4, 0x50, 0x84, 0x84, 0x76, 0x42, 0x84, 0x4e, 0xec, 0x80, 0x98, 0x1c, 0xed, 0x5c, 0xdc,
	0xc4, 0x65, 0x11, 0x8b, 0x1d, 0x6c, 0x17, 0xa9, 0x1f, 0x84, 0x03, 0x9f, 0x80, 0x2f, 0xc1, 0x87,
	0x23, 0x89, 0x5d, 0x62, 0x69, 0x88, 0x43, 0xb9, 0x39, 0xbf, 0xff, 0xf3, 0xff, 0xfd, 0xed, 0xe7,
	0x40, 0x20, 0xab, 0x6c, 0x5e, 0x49, 0xa1, 0x05, 0x8e, 0x28, 0xdf, 0x65, 0x74, 0x7d, 0xcb, 0xe2,
	0x9f, 0x1e, 0xdc, 0x4f, 0x04, 0xe7, 0x2c, 0xd3, 0x85, 0xe0, 0x84, 0x7d, 0xdd, 0x32, 0xa5, 0x11,
	0xe1, 0xb8, 0xa2, 0xfa, 0x26, 0xf2, 0xa6, 0xde, 0x2c, 0x20, 0xed, 0x1a, 0xdf, 0x82, 0x7f, 0xc3,
	0x68, 0xce, 0xa4, 0x8a, 0x7a, 0xd3, 0xfe, 0x2c, 0x5c, 0xcc, 0xe6, 0x7b, 0x97, 0xf9, 0x1d, 0x87,
	0xf9, 0x7b, 0x53, 0xba, 0xe4, 0x5a, 0xee, 0xc8, 0x7e, 0xe3, 0xe4, 0x1c, 0x4e, 0x5c, 0x01, 0xc7,
	0xd0, 0xff, 0xc2, 0x76, 0xb6, 0x4d, 0xb3, 0xc4, 0x07, 0x30, 0xf8, 0x46, 0x6f, 0xb7, 0xac, 0xee,
	0xd1, 0x30, 0xf3, 0x71, 0xde, 0x7b, 0xed, 0xc5, 0x9f, 0x00, 0xdd, 0x36, 0xaa, 0x12, 0x5c, 0x31,
	0x9c, 0xc1, 0x50, 0x69, 0xaa, 0xb7, 0xaa, 0x35, 0x39, 0x5d, 0x8c, 0xbb, 0x50, 0x69, 0xcb, 0x89,
	0xd5, 0x71, 0x0a, 0x61, 0x91, 0x33, 0xae, 0x8b, 0x4d, 0x61, 0xce, 0xd0, 0xf8, 0xbb, 0x28, 0xfe,
	0xee, 0xc1, 0x69, 0x22, 0xca, 0x92, 0xf2, 0xfc, 0x03, 0x53, 0x8a, 0x7e, 0x66, 0x18, 0x81, 0x9f,
	0x19, 0x62, 0x43, 0xee, 0x3f, 0xf1, 0x29, 0x40, 0xb7, 0xd7, 0xba, 0x39, 0x04, 0x5f, 0xc1, 0xa3,
	0xec, 0x4f, 0xdc, 0x95, 0xdb, 0xb9, 0xdf, 0xd6, 0x3e, 0xec, 0xd4, 0xcb, 0x4e, 0x6c, 0x6e, 0x3e,
	0xa7, 0x9a, 0x46, 0xc7, 0xe6, 0xe6, 0x9b, 0x75, 0xfc, 0xcb, 0x83, 0x7b, 0x36, 0xd7, 0x01, 0xe7,
	0xae, 0x83, 0xe6, 0x85, 0xb2, 0xdd, 0xda, 0xa0, 0x23, 0xe2, 0x10, 0x7c, 0x0e, 0x27, 0x4a, 0x8b,
	0x6a, 0xa5, 0xb4, 0x64, 0xb4, 0x34, 0xf1, 0x46, 0x24, 0x6c, 0x58, 0x6a, 0x10, 0x3e, 0x83, 0xd0,
	0xa8, 0xab, 0x8d, 0x14, 0x65, 0x9b, 0xad, 0xf6, 0x30, 0xe8, 0xa2, 0x26, 0x78, 0x06, 0x81, 0x2d,
	0x28, 0xf2, 0x68, 0xd0, 0x46, 0x1f, 0x19, 0x70, 0x99, 0xbf, 0x98, 0xc2, 0xd0, 0x44, 0xc2, 0x00,
	0x06, 0x4b, 0x42, 0x3e, 0x92, 0xf1, 0x11, 0x86, 0xe0, 0xa7, 0xd7, 0x49, 0xb2, 0x4c, 0xd3, 0xb1,
	0xb7, 0xf8, 0xd1, 0x83, 0x3e, 0xb9, 0x4a, 0xf0, 0x02, 0x7c, 0x3b, 0x62, 0x3c, 0xfb, 0xc7, 0xe3,
	0x9a, 0x3c, 0xf9, 0xbb, 0x68, 0xae, 0x26, 0x3e, 0xaa, 0x9f, 0x6a, 0x90, 0x6e, 0xd7, 0x2a, 0x93,
	0xc5, 0xba, 0x1e, 0xa1, 0x5b, 0xec, 0x0e, 0x77, 0xf2, 0xf8, 0x8e, 0xe2, 0x78, 0xbc, 0x83, 0xf0,
	0x9a, 0xab, 0xff, 0x75, 0x79, 0x03, 0xfe, 0x15, 0x93, 0x1b, 0x21, 0xcb, 0x03, 0x1d, 0xd6, 0xc3,
	0xf6, 0x8f, 0x7d, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xb5, 0x92, 0x1c, 0xbe, 0x03, 0x00,
	0x00,
}
