# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "anycable.ConnectionRequest" do
    optional :path, :string, 1
    map :headers, :string, :string, 2
  end
  add_message "anycable.ConnectionResponse" do
    optional :status, :enum, 1, "anycable.ConnectionStatus"
  end
  add_enum "anycable.ConnectionStatus" do
    value :ERROR, 0
    value :SUCCESS, 1
  end
end

module Anycable
  ConnectionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("anycable.ConnectionRequest").msgclass
  ConnectionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("anycable.ConnectionResponse").msgclass
  ConnectionStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("anycable.ConnectionStatus").enummodule
end
