# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: connector.proto for package 'anycable'

require 'grpc'
require_relative 'connector'

module Anycable
  module Connector

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'anycable.Connector'

      rpc :Connect, ConnectionRequest, ConnectionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
